name: contributors
on: 
    push:
        branches:
        - master
jobs:
    contrib-readme-job:
        runs-on: ubuntu-latest
        permissions:
          contents: write
          pull-requests: write
        name: A job to automate contrib in readme
        steps:
            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@v2.3.11
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}