name: build
on: 
  push:
    branches:
      - master
    tags:
    - '!*' # Do not execute on tags
    paths:
    - source/*
    - test/*
    - '*.json'
    - package.lock
    - .github/workflows/*
  pull_request:

jobs:
    build:
        name: Node.js ${{ matrix.node-version }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version:
                    - 16
                    - 18
                    - 20
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v6
              with:
                node-version: ${{ matrix.node-version }}
            - run: yarn
            - run: yarn build
    coverage:
        needs: [ build ]
        name: coverage
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-node@v6
              with:
                node-version: '18'
            - run: yarn
            - run: yarn test
            - uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
